version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  favourites-api:
    image: sonerd/favourites-api
    #container_name: favourites-api
    build:
      context: ./favourites-api
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=favourites-api.company.com
      - VIRTUAL_PORT=8282
    ports:
      - 8282
    depends_on:
      - auth.company.com

  favourites-app:
      image: sonerd/favourites-app
      #container_name: favourites-app
      build:
        context: ./favourites-app
        dockerfile: Dockerfile
      environment:
        - VIRTUAL_HOST=favourites-app.company.com
        - VIRTUAL_PORT=8383
      ports:
        - 8383
        - "8000:8000"
      depends_on:
        - auth.company.com

  auth.company.com:
    build:
      context: .
      dockerfile: Dockerfile
    image: sonerd/keycloak-auth
    hostname: auth.company.com
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/sample-realm.json
      - PROXY_ADDRESS_FORWARDING=true
      - VIRTUAL_HOST=auth.company.com
      - VIRTUAL_PORT=8080
